apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: puz1p9268-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: puz1p9268-go 
  name: puz1p9268-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: puz1p9268-go 
