apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: puz1p9268-go 
  janus-idp.io/tekton: puz1p9268-go
  backstage.io/kubernetes-id: puz1p9268-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: puz1p9268-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml