apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: puz1p9268-go-gitops
  description: This is GitOps manifest for puz1p9268-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-selector: rhtap/gitops=puz1p9268-go
    backstage.io/kubernetes-id: puz1p9268-go 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: puz1p9268-go   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:puz1p9268-go
